action_and_flowrate_topic='/rig1'
delay_before_first_pulse=10*60
pulse_length=10*60
inter_pulse_length=40*60
total_experiment_length=24*60*60
#flowrates="[0.2, 1, 3]"
flowrates="[1]"
randomize_flowrate_order=True
off_action='off'
on_actions="['right', 'left']"
randomize_on_actions_order=False
